export const newsConstants = {
    GET_ALL_NEWS : 'GET_ALL_NEWS',
    GET_ALL_REQUEST_SUCCESS : 'GET_ALL_REQUEST_SUCCESS',
    SET_CURRENT_PAGE : 'SET_CURRENT_PAGE',
    SET_VISIBLE_NEWS : 'SET_VISIBLE_NEWS'
};