export const userConstants = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USER_LOGOUT',

    REQUEST_USER_DATA: 'USER_DATA_REQUEST',
    REQUEST_USER_DATA_SUCCESS: 'USER_DATA_REQUEST_SUCCESS'
};